### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by kingmanzhang** [monarch-initiative/HpoTextMining#8]
The master branch gives me this error:
08:32:19.857 [JavaFX Application Thread] INFO  org.monarchinitiative.phenol.graph.util.CompatibilityChecker - Checking vertices (13757) and edges (17630) for compatibility...
08:32:19.873 [JavaFX Application Thread] INFO  org.monarchinitiative.phenol.graph.util.CompatibilityChecker - Vertices and edges are compatible!
08:32:19.884 [JavaFX Application Thread] INFO  org.monarchinitiative.phenol.graph.util.CompatibilityChecker - Graph is simple!
08:32:22.032 [JavaFX Application Thread] INFO  com.github.monarchinitiative.hpotextmining.gui.controller.HpoTextMining - Using 'https://scigraph-ontology.monarchinitiative.org/scigraph/annotations/complete' as url for text mining server
08:32:27.209 [pool-3-thread-1] WARN  com.github.monarchinitiative.hpotextmining.core.miners.scigraph.SciGraphTermMiner - Protocol exception
java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1298) ~[?:1.8.0_144]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) ~[?:1.8.0_144]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[?:1.8.0_144]
	at com.github.monarchinitiative.hpotextmining.core.miners.scigraph.SciGraphTermMiner.doMining(SciGraphTermMiner.java:99) [classes/:?]
	at com.github.monarchinitiative.hpotextmining.core.miners.scigraph.SciGraphTermMiner.doMining(SciGraphTermMiner.java:28) [classes/:?]
	at com.github.monarchinitiative.hpotextmining.gui.controller.Configure$1.call(Configure.java:80) [classes/:?]
	at com.github.monarchinitiative.hpotextmining.gui.controller.Configure$1.call(Configure.java:77) [classes/:?]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
08:32:27.213 [JavaFX Application Thread] WARN  com.github.monarchinitiative.hpotextmining.gui.controller.Configure - Text mining analysis failed. 
08:32:27.213 [JavaFX Application Thread] WARN  com.github.monarchinitiative.hpotextmining.gui.controller.HpoTextMining - Sorry, text mining analysis failed.
Approved terms:

**Comment by ielis** [comment]
Hi Aaron, funny how a single line can do that much mess. Does it please work now?
Cheers

**Comment by kingmanzhang** [comment]
Yes!
